// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1S57sRzX467N4RXnYkukRQnXYxyBJceE',
    appId: '1:691489374621:web:e66ed39779953535886f74',
    messagingSenderId: '691489374621',
    projectId: 'todo-f0924',
    authDomain: 'todo-f0924.firebaseapp.com',
    storageBucket: 'todo-f0924.appspot.com',
    measurementId: 'G-LZ2SKFN4CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAzO2-uup0MBtCutzcKriBuh6PhAM6WI',
    appId: '1:691489374621:android:2725f735bf7a0eab886f74',
    messagingSenderId: '691489374621',
    projectId: 'todo-f0924',
    storageBucket: 'todo-f0924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRbZwvzJTyaLz7IoezA56cuZcIziIAuDU',
    appId: '1:691489374621:ios:55b94f556d99acbb886f74',
    messagingSenderId: '691489374621',
    projectId: 'todo-f0924',
    storageBucket: 'todo-f0924.appspot.com',
    iosBundleId: 'com.example.journeyIi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRbZwvzJTyaLz7IoezA56cuZcIziIAuDU',
    appId: '1:691489374621:ios:4ea0ef882e80e330886f74',
    messagingSenderId: '691489374621',
    projectId: 'todo-f0924',
    storageBucket: 'todo-f0924.appspot.com',
    iosBundleId: 'com.example.journeyIi.RunnerTests',
  );
}
